name: CI

on:
  push: {branches: master}
  pull_request: {branches: master}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '16.x'
      - run: node -v
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}
          restore-keys: ${{runner.os}}-npm-
      - run: cd jp-front-end
      - run: npm ci
      - run: ng build