name: CI

on:
  push: 
    branches: 
      - master
      - feature/aws-deploy
  pull_request: {branches: master}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: {node-version: 13.x}
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}
          restore-keys: ${{runner.os}}-npm-
      - name: Build Angular App
        working-directory: jp-front-end
        run: npm ci && npm run build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: jp-front-end/dist/jp-front-end
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Artifact Download 
        uses: actions/download-artifact@v2
        with: 
          name: dist
          path: jp-front-end/dist/jp-front-end
      - name: AWS S3 Deploy
        working-directory: jp-front-end
        run: aws s3 sync ./dist/jp-front-end s3://jamespicadevelopment.com --delete